openapi: 3.0.0
info:
  title: Antna ICE - Invoice/Note Reporting API 1.0
  description: |-
    This is a test API for Reporting Invoice/Note with ZATCA's Fatoora Portal. 
    
    Some useful links for reference:
    - [Blogs](https://blog.antna.co.in/)
    - [Youtube Playlist](https://www.youtube.com/watch?v=QXdEyqZ2gs0&list=PLu4vz4jylcs4GuAyuUJbhKQOQImJexEt4)
  termsOfService: https://www.antna.co.in/terms.html
  contact:
    email: support@antna.co.in
  license:
    name: License
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT
servers:
  - url: https://kixq9sqvjc.execute-api.ap-south-1.amazonaws.com/test
tags:
  - name: Invoice/Note
    description: Reporting/Clearance for Invoice/Note with ZATCA's Fatoora Portal
    externalDocs:
      description: Find out more about our store
      url: http://antna.co.in
paths:
  /api/v1/proto/csrRequest:
    post:
      tags:
        - Onboarding
      summary: CsrReq
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                csrInputs:
                  otp: '123345'
                  commonName: TST-886431145-300055184400003
                  serialNumber: 1-TST|2-TST|3-ed22f1d8-e6a2-1118-9b58-d9a8f11e445f
                  organizationIdentifier: '300055184400003'
                  organizationUnitName: '3123456789'
                  organizationName: '3123456789'
                  countryName: SA
                  invoiceType: '1111'
                  location: TST
                  industry: TST
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          headers:
            Date:
              schema:
                type: string
                example: Wed, 26 Oct 2022 05:10:17 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '32'
            Connection:
              schema:
                type: string
                example: keep-alive
            x-amzn-RequestId:
              schema:
                type: string
                example: 0beb71fd-3142-4bfe-9733-38110050387e
            x-amz-apigw-id:
              schema:
                type: string
                example: amMf4HXLhcwFWTQ=
            X-Amzn-Trace-Id:
              schema:
                type: string
                example: Root=1-6358c132-5950e1cf30dc3d414c1a349b;Sampled=0
          content:
            application/json:
              schema:
                type: object
              example:
                status: SUCCESS
                errors: []
        '400':
          description: BAD REQUEST
          headers:
            Date:
              schema:
                type: string
                example: Wed, 26 Oct 2022 05:10:17 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '32'
            Connection:
              schema:
                type: string
                example: keep-alive
            x-amzn-RequestId:
              schema:
                type: string
                example: 0beb71fd-3142-4bfe-9733-38110050387e
            x-amz-apigw-id:
              schema:
                type: string
                example: amMf4HXLhcwFWTQ=
            X-Amzn-Trace-Id:
              schema:
                type: string
                example: Root=1-6358c132-5950e1cf30dc3d414c1a349b;Sampled=0
          content:
            application/json:
              schema:
                type: object
              example:
                  summary: CsrReq
                  value:
                    status: ERROR
                    errors:
                      - code: 400 BAD_REQUEST
                        message: OTP is required field        
  /api/v1/proto/reportDocument:
    post:
      tags:
        - Invoice/Note
      summary: Report Document
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                invoiceData:
                  documentType: SIMPLIFIED_TAX_INVOICE
                  referenceId: ''
                  documentIssueDateTime: '2022-10-21T12:53:13.000Z'
                  documentDueDateTime: '2022-10-26T12:53:13.000Z'
                  sellerName: Company Name
                  sellerAddress:
                    addrLine1: Makkah
                    addrLine2: Al Alam Street
                    city: Riyadh
                    state: Riyadh
                    zipCode: '24211'
                    phone: '2121'
                    fax: '8228'
                    district: Riyadh
                    country: Saudi Arabia
                    additionalNo: ''
                  buyerName: Antna
                  buyerAddress:
                    attention: Meiyappan MM
                    countryOrRegion: SA
                    addrLine1: 12, Masjid Street
                    addrLine2: Amjad Building
                    city: Dammam
                    state: Riyadh
                    zipCode: '12313'
                    phone: '2121'
                    fax: '8228'
                    district: Riyadh
                    country: SA
                  documentLineItems:
                    - lineItemDesc: Ball point pen
                      lineItemPrice: 10
                      lineItemQty: 10
                      lineItemTaxableAmount: 100
                      discountOnLineItem: 0
                      vatRateOnLineItem: 15
                      lineItemVatAmount: 15
                      lineItemSubTotal: 115
                  totalExcludingVat: 100
                  totalTaxableAmountExcludingVat: 100
                  vatTotal: 15
                  documentTotal: 115
                  isSpecialBillingAgreement: 'false'
                  isTransactionType: 'false'
                  isSelfBilled: 'false'
                  isThirdParty: 'true'
                  isNominalSupply: 'false'
                  isExport: 'false'
                  isSummary: 'false'
                  supplyDate: '2022-10-21T12:53:13.000Z'
                  sellerVatRegistrationNumber: '300055184400003'
                  sellerGroupVatRegistrationNumber: ''
                  buyerVatRegistrationNumber: '300244974200003'
                  buyerGroupVatRegistrationNumber: '300244974200003'
                  discountOnDocumentTotal: 0
                  specialTaxTreatment: '0'
                  currency: SAR
                  documentId: 2022100627
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          headers:
            Date:
              schema:
                type: string
                example: Wed, 26 Oct 2022 05:19:17 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '349'
            Connection:
              schema:
                type: string
                example: keep-alive
            x-amzn-RequestId:
              schema:
                type: string
                example: 9b13af08-ab14-4239-9405-753724aed80b
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Headers:
              schema:
                type: string
                example: >-
                  Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,x-requested-with,UUID
            x-amz-apigw-id:
              schema:
                type: string
                example: amNzJETWhcwFkUQ=
            Access-Control-Allow-Methods:
              schema:
                type: string
                example: DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT, ANY
            Access-Control-Expose-Headers:
              schema:
                type: string
                example: >-
                  Access-Control-Allow-Origin, Access-Control-Allow-Headers,
                  Access-Control-Allow-Methods
            X-Amzn-Trace-Id:
              schema:
                type: string
                example: Root=1-6358c347-39ad97b1376e30fd0f0f5d4b;Sampled=0
          content:
            application/json:
              schema:
                type: object
              examples:
                example-0:
                  summary: Report Document
                  value:
                    zatcaResponse:
                      validationResults:
                        infoMessages:
                          - type: INFO
                            code: XSD_ZATCA_VALID
                            category: XSD validation
                            message: >-
                              Complied with UBL 2.1 standards in line with ZATCA
                              specifications
                            status: PASS
                        warningMessages: []
                        errorMessages: []
                        status: PASS
                      reportingStatus: REPORTED
                      timestamp: 0
                      status: 0
                    isReported: true
                example-1:
                  summary: Report Document
                  value:
                    isReported: false
  /api/v1/proto/generateQRCode:
    post:
      tags:
        - QR Code
      summary: QR Code(Simplified Invoice)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                invoiceData:
                  documentType: SIMPLIFIED_TAX_INVOICE
                  referenceId: ''
                  documentIssueDateTime: '2022-10-21T12:53:13.000Z'
                  documentDueDateTime: '2022-10-26T12:53:13.000Z'
                  sellerName: Company Name
                  sellerAddress:
                    addrLine1: Makkah
                    addrLine2: Al Alam Street
                    city: Riyadh
                    state: Riyadh
                    zipCode: '24211'
                    phone: '2121'
                    fax: '8228'
                    district: Riyadh
                    country: Saudi Arabia
                    additionalNo: ''
                  buyerName: Antna
                  buyerAddress:
                    attention: Meiyappan MM
                    countryOrRegion: SA
                    addrLine1: 12, Masjid Street
                    addrLine2: Amjad Building
                    city: Dammam
                    state: Riyadh
                    zipCode: '12313'
                    phone: '2121'
                    fax: '8228'
                    district: Riyadh
                    country: SA
                  documentLineItems:
                    - lineItemDesc: Ball point pen
                      lineItemPrice: 10
                      lineItemQty: 10
                      lineItemTaxableAmount: 100
                      discountOnLineItem: 0
                      vatRateOnLineItem: 15
                      lineItemVatAmount: 15
                      lineItemSubTotal: 115
                  totalExcludingVat: 100
                  totalTaxableAmountExcludingVat: 100
                  vatTotal: 15
                  documentTotal: 115
                  isSpecialBillingAgreement: 'false'
                  isTransactionType: 'false'
                  isSelfBilled: 'false'
                  isThirdParty: 'true'
                  isNominalSupply: 'false'
                  isExport: 'false'
                  isSummary: 'false'
                  supplyDate: '2022-10-21T12:53:13.000Z'
                  sellerVatRegistrationNumber: '300055184400003'
                  sellerGroupVatRegistrationNumber: ''
                  buyerVatRegistrationNumber: '300244974200003'
                  buyerGroupVatRegistrationNumber: '300244974200003'
                  discountOnDocumentTotal: 0
                  specialTaxTreatment: '0'
                  currency: SAR
                  documentId: 2022100627
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          headers:
            Date:
              schema:
                type: string
                example: Thu, 03 Nov 2022 04:09:31 GMT
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: '433'
            Connection:
              schema:
                type: string
                example: keep-alive
            x-amzn-RequestId:
              schema:
                type: string
                example: 5cd50847-9ae0-4658-a452-2d8514d1f733
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: '*'
            Access-Control-Allow-Headers:
              schema:
                type: string
                example: >-
                  Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,x-requested-with,UUID
            x-amz-apigw-id:
              schema:
                type: string
                example: bAbHIGn-hcwFseQ=
            Access-Control-Allow-Methods:
              schema:
                type: string
                example: DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT, ANY
            Access-Control-Expose-Headers:
              schema:
                type: string
                example: >-
                  Access-Control-Allow-Origin, Access-Control-Allow-Headers,
                  Access-Control-Allow-Methods
            X-Amzn-Trace-Id:
              schema:
                type: string
                example: Root=1-63633efa-0f4fd26f2a1ba8085aaae8cd;Sampled=0
          content:
            application/json:
              schema:
                type: object
              example:
                encodedQrCodeData: >-
                  AQxDb21wYW55IE5hbWUCDzMwMDA1NTE4NDQwMDAwMwMUMjAyMi0xMC0yMVQwMDo1MzoxM1oEBjExNS4wMAUFMTUuMDAGLE9QUVJpUjRlVVpnL01QbXE1eStqMlVKTlZlOGxZbGF5ZkFiZ3pnTkFpdTQ9B2BNRVlDSVFDYzFJdlM3RVVGbXVGK0NHaDlCT0x5TUQ2UkF6elFvS043ckpmOXdZaXZjUUloQU9wdFkrbGx2bXd2TXZVaThvZjFWUFZCa1d0c1NjSXprSUZkSU1HOFR1emkIWDBWMBAGByqGSM49AgEGBSuBBAAKA0IABA/8G9pYQbwSAvAp52b6LqOjs0cpsplPTVkYSMmjIRkRAQhGQeBAFawbldsV4sWOKgWH/XXXq85FvQ8HaNyJR4I=
